include: package:very_good_analysis/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
  language:
    strict-raw-types: false
  exclude:
    - "lib/ignored_widget.dart"
custom_lint:
  rules:
    - 110_lines_limit_in_widgets: true