name: line_limit_lint
description: "Lint rule, designed to highlight widget files that exceed a specified size threshold."
version: 0.0.2
homepage: https://github.com/leredirect/line_counter_lint

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.5.11
